import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Menu from 'components/Menu/Menu'
import { useState } from 'react'

export default function Home() {
const [active, setActive] = useState(false)

  return (
    <div className={active?`${styles.container} ${styles.active}`: styles.container} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu active={setActive} />
      <div style={{width: "100%", height: "100vh"}}></div>
    </div>
  )
}
