import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Menu,
  HeroSection,
  AboutMe,
  ProjectsSection,
  SkillsSection,
  ContactMeSection,
  Footer,
  Layout,
} from "components";
import { useState } from "react";

export default function Home() {
  const [active, setActive] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.container}
      >
        <Menu active={setActive} />
        <Layout isActive={active}>
          <HeroSection />
          <AboutMe />
          <ProjectsSection />
          <SkillsSection />
          <ContactMeSection />
          <Footer />
        </Layout>
      </div>
    </>
  );
}
